[package]
name = "rs3"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
aws-config = "1"
aws-credential-types = "1"
aws-sdk-s3 = "1"
aws-smithy-types = { version = "1", features = ["http-body-1-x"] }
base64 = "0.22"
bytes = "1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4", features = ["derive", "wrap_help"] }
dirs = "6"
flate2 = "1"
futures = "0.3"
hmac = "0.12"
http-body = "1"
humansize = "2"
indicatif = "0.17"
percent-encoding = "2"
pin-project-lite = "0.2"
regex = "1"
sha2 = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
shell-words = "1"
tokio = { version = "1", features = ["fs", "io-std", "io-util", "macros", "rt-multi-thread"] }

[dev-dependencies]
tempfile = "3"
