#![allow(dead_code)]
use std::io::{Read, Write};
use std::net::TcpListener;
use std::path::PathBuf;
use std::process::{Child, Command, Output, Stdio};
use std::time::{Duration, Instant};

pub struct TestServer {
    child: Child,
    pub port: u16,
    pub dir: tempfile::TempDir,
    pub access_key: String,
    pub secret_key: String,
}

fn free_port() -> u16 {
    let listener = TcpListener::bind("127.0.0.1:0").expect("bind ephemeral port");
    listener.local_addr().expect("local addr").port()
}

/// `free_port()` binds an ephemeral port and immediately drops the
/// listener, then `rusts3` binds it moments later. If two tests race that
/// window, both can be handed the same OS-assigned port; whichever
/// `rusts3` binds first wins, and the loser exits immediately with
/// `AddrInUse`. `TestServer::start` retries the loser with a fresh port
/// (see `wait_ready`), but that alone isn't enough: with a shared literal
/// `testkey`/`testsecret` credential, the LOSING test's `wait_ready` probe
/// would succeed against the WINNING test's server (same creds, and by
/// then the same port in its own `MC_HOST_TEST`), silently pointing that
/// test at someone else's server for its whole run -- e.g. `rb --dangerous`
/// deleting another test's buckets. Deriving per-instance credentials from
/// each `TestServer`'s own tempdir (whose suffix is already
/// collision-resistant, generated by the `tempfile` crate before any port
/// is chosen) means a cross-wired connection fails auth instead of
/// silently succeeding.
fn unique_suffix(dir: &tempfile::TempDir) -> String {
    dir.path()
        .file_name()
        .and_then(|n| n.to_str())
        .map(str::to_string)
        .unwrap_or_else(|| format!("{}", std::process::id()))
}

enum ReadyOutcome {
    Ready,
    /// The child process exited before the server ever became reachable --
    /// the signature of a lost bind-port race. Carries a diagnostic for the
    /// final panic message if retries are exhausted.
    ExitedEarly(String),
    /// The child is still running but never answered `ls` within the
    /// deadline -- a genuine startup/hang failure, not a bind race. Not
    /// worth retrying: surfaced immediately.
    TimedOut(String),
}

fn rusts3_binary() -> PathBuf {
    if let Ok(bin) = std::env::var("RUSTS3_BIN") {
        return PathBuf::from(bin);
    }
    // client/ crate root -> repo root
    let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("client has parent")
        .to_path_buf();
    let bin = repo_root.join("target/release/rusts3");
    if !bin.exists() {
        let status = Command::new("cargo")
            .args(["build", "--release"])
            .current_dir(&repo_root)
            .status()
            .expect("run cargo build for rusts3");
        assert!(status.success(), "building rusts3 failed");
    }
    bin
}

impl TestServer {
    pub fn start() -> Self {
        const MAX_BIND_ATTEMPTS: u32 = 5;
        let mut last_failure = String::new();
        for attempt in 1..=MAX_BIND_ATTEMPTS {
            let dir = tempfile::tempdir().expect("create temp dir");
            let suffix = unique_suffix(&dir);
            let access_key = format!("testkey{suffix}");
            let secret_key = format!("testsecret{suffix}");
            let port = free_port();
            let config = format!(
                "server:\n  bind_address: 127.0.0.1\n  bind_port: {port}\n  base_dir: {data}\nui:\n  enabled: false\nauth:\n  enabled: true\n  credentials:\n    - access_key: {access_key}\n      secret_key: {secret_key}\nlogging:\n  level: warn\n  enable_bandwidth_report: false\n",
                data = dir.path().join("data").display()
            );
            let config_path = dir.path().join("config.yaml");
            std::fs::File::create(&config_path)
                .and_then(|mut f| f.write_all(config.as_bytes()))
                .expect("write server config");
            let child = Command::new(rusts3_binary())
                .args(["run", "-c"])
                .arg(&config_path)
                .stdout(Stdio::null())
                .stderr(Stdio::piped())
                .spawn()
                .expect("spawn rusts3");
            let mut server = TestServer {
                child,
                port,
                dir,
                access_key,
                secret_key,
            };
            match server.wait_ready() {
                ReadyOutcome::Ready => return server,
                ReadyOutcome::ExitedEarly(msg) => {
                    // Almost certainly a lost bind-port race (see
                    // `unique_suffix`'s doc comment): drop this attempt
                    // (killing/reaping the dead child and cleaning up its
                    // tempdir) and retry with a fresh port.
                    last_failure = format!("attempt {attempt} on port {port}: {msg}");
                }
                ReadyOutcome::TimedOut(msg) => {
                    // The child is alive but never became ready -- a real
                    // failure, not a port race. No point retrying.
                    panic!("{msg}");
                }
            }
        }
        panic!(
            "rusts3 failed to bind after {MAX_BIND_ATTEMPTS} attempts (repeated bind-port \
             races): {last_failure}"
        );
    }

    pub fn alias(&self) -> &'static str {
        "test"
    }

    /// The `alias://` URL rs3 itself would generate for this server (used
    /// by tests that need to build their own `Command` rather than going
    /// through `rs3`/`rs3_ok`).
    pub fn mc_host(&self) -> String {
        format!(
            "http://{}:{}@127.0.0.1:{}",
            self.access_key, self.secret_key, self.port
        )
    }

    fn wait_ready(&mut self) -> ReadyOutcome {
        let deadline = Instant::now() + Duration::from_secs(30);
        loop {
            if let Ok(Some(status)) = self.child.try_wait() {
                let mut stderr = String::new();
                if let Some(mut s) = self.child.stderr.take() {
                    let _ = s.read_to_string(&mut stderr);
                }
                return ReadyOutcome::ExitedEarly(format!(
                    "rusts3 exited early ({status}) on port {}: {stderr}",
                    self.port
                ));
            }
            let out = self.rs3(&["ls", "test/"]);
            if out.status.success() {
                return ReadyOutcome::Ready;
            }
            if Instant::now() >= deadline {
                return ReadyOutcome::TimedOut(format!(
                    "rusts3 did not become ready on port {}: {}",
                    self.port,
                    String::from_utf8_lossy(&out.stderr)
                ));
            }
            std::thread::sleep(Duration::from_millis(200));
        }
    }

    pub fn rs3(&self, args: &[&str]) -> Output {
        Command::new(env!("CARGO_BIN_EXE_rs3"))
            .args(args)
            .env("MC_HOST_TEST", self.mc_host())
            .env("MC_CONFIG_DIR", self.dir.path().join("mc-config"))
            .output()
            .expect("run rs3")
    }

    pub fn rs3_ok(&self, args: &[&str]) -> String {
        let out = self.rs3(args);
        assert!(
            out.status.success(),
            "rs3 {:?} failed:\nstdout: {}\nstderr: {}",
            args,
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr)
        );
        String::from_utf8_lossy(&out.stdout).into_owned()
    }

    /// Directly PUT a zero-byte folder-marker object (key ending in `/`)
    /// using the aws-sdk-s3 crate, bypassing rs3's own `put` command (which
    /// has no way to create a key ending in `/`). Used to reproduce
    /// marker-object bugs that only manifest against a real S3-compatible
    /// server.
    pub fn put_marker(&self, bucket: &str, key: &str) {
        use aws_config::{BehaviorVersion, Region};
        use aws_credential_types::Credentials;
        use aws_sdk_s3::Client;
        use aws_sdk_s3::config::SharedCredentialsProvider;
        use aws_sdk_s3::primitives::ByteStream;

        let bucket = bucket.to_string();
        let key = key.to_string();
        let port = self.port;
        let access_key = self.access_key.clone();
        let secret_key = self.secret_key.clone();
        tokio::runtime::Runtime::new()
            .unwrap()
            .block_on(async move {
                let creds = Credentials::new(access_key, secret_key, None, None, "rs3-test");
                let sdk_cfg = aws_config::defaults(BehaviorVersion::latest())
                    .region(Region::new("us-east-1"))
                    .credentials_provider(SharedCredentialsProvider::new(creds))
                    .load()
                    .await;
                let s3_cfg = aws_sdk_s3::config::Builder::from(&sdk_cfg)
                    .endpoint_url(format!("http://127.0.0.1:{port}"))
                    .force_path_style(true)
                    .build();
                let client = Client::from_conf(s3_cfg);
                client
                    .put_object()
                    .bucket(bucket)
                    .key(key)
                    .body(ByteStream::from_static(b""))
                    .send()
                    .await
                    .expect("put marker object");
            });
    }
}

/// Start (but never complete) a multipart upload directly via the
/// aws-sdk-s3 crate, bypassing rs3's own `put` command (which has no way to
/// leave an upload dangling). Used to reproduce `ls --incomplete` against a
/// real in-progress multipart upload.
pub fn start_incomplete_multipart(server: &TestServer, bucket: &str, key: &str) {
    use aws_config::{BehaviorVersion, Region};
    use aws_credential_types::Credentials;
    use aws_sdk_s3::Client;
    use aws_sdk_s3::config::SharedCredentialsProvider;

    let bucket = bucket.to_string();
    let key = key.to_string();
    let port = server.port;
    let access_key = server.access_key.clone();
    let secret_key = server.secret_key.clone();
    tokio::runtime::Runtime::new()
        .unwrap()
        .block_on(async move {
            let creds = Credentials::new(access_key, secret_key, None, None, "rs3-test");
            let sdk_cfg = aws_config::defaults(BehaviorVersion::latest())
                .region(Region::new("us-east-1"))
                .credentials_provider(SharedCredentialsProvider::new(creds))
                .load()
                .await;
            let s3_cfg = aws_sdk_s3::config::Builder::from(&sdk_cfg)
                .endpoint_url(format!("http://127.0.0.1:{port}"))
                .force_path_style(true)
                .build();
            let client = Client::from_conf(s3_cfg);
            client
                .create_multipart_upload()
                .bucket(bucket)
                .key(key)
                .send()
                .await
                .expect("create multipart upload");
        });
}

impl Drop for TestServer {
    fn drop(&mut self) {
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}
